#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'

require 'prawler'

repos = (ENV['REPOS'] || '').split(',').map(&:strip)
repos = repos.present? ? repos : nil

login = (ENV['LOGIN'] || '').strip
login = login.present? ? login : nil

values = {}
options = OptionParser.new do |opts|
  opts.banner = 'Usage prawler [options]'

  opts.on('-a', '--approved', 'only approved pull requests') do |v|
    values[:approved] = v
  end

  opts.on('-v', '--verbose', 'useful information') do |v|
    values[:verbose] = v
  end
end
options.parse!

questions = Prawler::Application
  .new(repos, login)
  .questionnaire
  .open_pull_requests

questions = questions.approved_reviews if values.fetch(:approved, false)

if values.fetch(:verbose, false)
  questions
    .to_a
    .each { |pr| puts "#{pr.number} | #{pr.title} | state = #{pr.state} | #{pr.html_url}" }
else
  questions
    .to_a
    .each { |pr| puts pr.html_url }
end
